function [fitresult, gof] = fullFitPFF(x, y)
%CREATEFIT1(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Jul-2024 16:19:10


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'a1*voigtian(x,x0,wg1,wl1)+a2*voigtian(x,2.*x0,wg2,wl2)+a3*voigtian(x,3.*x0,wg3,wl3)+a4*voigtian(x,4.*x0,wg4,wl4)+a5*voigtian(x,5.*x0,wg5,wl5)+app*voigtian(x,xpp,wgpp,wlpp)+b0+b1.*x+b2.*x.^2+b3.*x.^3', 'independent', 'x', 'dependent', 'y' );
excludedPoints = (xData < 0.3) | (xData > 2.5);
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0 -Inf -Inf -Inf -Inf 0 0 0 0 0 0 0 0 0 0 0 0 0.26 1.6];
opts.MaxFunEvals = 60000;
opts.MaxIter = 40000;
opts.StartPoint = [120 15 10 5 5 25 0 0 0 0 0.01 0.01 0.01 0.01 0.01 0.1 0.1 0.1 0.1 0.1 0.1 0.05 0.32 1.77];
opts.TolFun = 1e-12;
opts.TolX = 1e-12;
opts.Upper = [Inf Inf Inf 25 25 Inf Inf Inf Inf Inf 1 1 1 1 1 1 1 1 1 1 Inf Inf 0.35 2];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData, excludedPoints );
legend( h, 'y vs. x', 'Excluded y vs. x', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x', 'Interpreter', 'none' );
ylabel( 'y', 'Interpreter', 'none' );
grid on


