function [fitresult, gof] = lamellarFit3Order(x, y)
%CREATEFIT1(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-May-2024 16:08:42


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'a1*voigtian(x,x0,wg1,wl1)+a2*voigtian(x,2.*x0,wg2,wl2)+a3*voigtian(x,3.*x0,wg3,wl3)+giwaxsBackground(x,b1,l,b2,k)', 'independent', 'x', 'dependent', 'y' );
excludedPoints = xData < 0.32;
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0 0 0 0 0 0 0 0 0.33];
opts.MaxFunEvals = 6000;
opts.MaxIter = 4000;
opts.StartPoint = [300 50 20 30000000 115 -0.2 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.34];
opts.TolFun = 1e-12;
opts.TolX = 1e-12;
opts.Upper = [Inf Inf Inf Inf Inf Inf Inf 0.2 0.2 0.2 0.2 0.2 0.2 0.4];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData, excludedPoints );
legend( h, 'y vs. x', 'Excluded y vs. x', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x', 'Interpreter', 'none' );
ylabel( 'y', 'Interpreter', 'none' );
grid on


