function [fitresult, gof] = pipiBackboneFit_TaylorBackground(x, y)
%CREATEFIT1(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Jul-2024 14:30:46


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'a1.*voigtian(x,c1,wg1,wl1)+a2.*voigtian(x,c2,wg2,wl2)+b0+b1.*x+b2.*x^2+b3.*x^3', 'independent', 'x', 'dependent', 'y' );
excludedPoints = (xData < 0.25) | (xData > 2.5);
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.DiffMinChange = 1e-12;
opts.Display = 'Off';
opts.Lower = [0 0 -Inf -Inf -Inf -Inf 1.25 1.55 0 0 0 0];
opts.MaxFunEvals = 10000;
opts.MaxIter = 5000;
opts.StartPoint = [1 1 0.694828622975817 40 40 0.317099480060861 1.45 1.66 0.01 0.01 0.02 0.02];
opts.TolFun = 1e-12;
opts.TolX = 1e-12;
opts.Upper = [Inf Inf Inf Inf Inf Inf 1.55 2 0.5 0.5 0.5 0.5];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData, excludedPoints );
legend( h, 'y vs. x', 'Excluded y vs. x', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x', 'Interpreter', 'none' );
ylabel( 'y', 'Interpreter', 'none' );
grid on


