function [fitresult, gof] = pipiBackboneHaloFit(x, y)
%CREATEFIT1(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-May-2024 18:36:23


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'a1.*voigtian(x,x01,wg1,wl1)+a2.*voigtian(x,x02,wg2,wl2)+a3.*voigtian(x,x03,wg3,wl3)+giwaxsBackground(x,b1,l,b2,k)', 'independent', 'x', 'dependent', 'y' );
excludedPoints = xData < 0.2;
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0 0 0 0 0 0 0 0 1.51 1.6 1];
opts.MaxFunEvals = 5000;
opts.MaxIter = 5000;
opts.StartPoint = [0.5 10 25 100 100 0.1 0.94 0.02 0.06 0.5 0.02 0.06 0.5 1.54 1.75 1.6];
opts.TolFun = 1e-12;
opts.TolX = 1e-12;
opts.Upper = [Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf 1.55 2 1.7];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData, excludedPoints );
legend( h, 'y vs. x', 'Excluded y vs. x', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x', 'Interpreter', 'none' );
ylabel( 'y', 'Interpreter', 'none' );
grid on


