function [fitresult, gof] = pipiHaloPFF(x, y)
%CREATEFIT1(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Jul-2024 15:12:42


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'a1.*voigtian(x,c1,wg1,wl1)+a2.*voigtian(x,c2,wg2,wl2)+b0+b1.*x+b2.*x^2+b3.*x^3', 'independent', 'x', 'dependent', 'y' );
excludedPoints = (xData < 1) | (xData > 2.5);
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.DiffMinChange = 1e-12;
opts.Display = 'Off';
opts.Lower = [0 0 -Inf -Inf -Inf -Inf 1 1.55 -Inf -Inf -Inf -Inf];
opts.MaxFunEvals = 10000;
opts.MaxIter = 5000;
opts.StartPoint = [0.929263623187228 0.349983765984809 0.196595250431208 0.251083857976031 0.616044676146639 0.473288848902729 0.351659507062997 0.830828627896291 0.585264091152724 0.54972360829114 0.91719366382981 0.285839018820374];
opts.TolFun = 1e-12;
opts.TolX = 1e-12;
opts.Upper = [Inf Inf Inf Inf Inf Inf 1.55 2 Inf Inf Inf Inf];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData, excludedPoints );
legend( h, 'y vs. x', 'Excluded y vs. x', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x', 'Interpreter', 'none' );
ylabel( 'y', 'Interpreter', 'none' );
grid on


